    #!/bin/bash
    set -e # Stop het script onmiddellijk als een commando faalt
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- === Database voor Core-Geheugen ===
    CREATE USER ${CORE_USER_NAME} WITH PASSWORD '${CORE_USER_PASSWORD}';
    CREATE DATABASE ${CORE_MEMORY_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${CORE_MEMORY_DB_NAME} TO ${CORE_USER_NAME};
    ALTER DATABASE ${CORE_MEMORY_DB_NAME} OWNER TO ${CORE_USER_NAME};
    -- === Gebruiker & Database voor n8n ===
    CREATE USER ${N8N_DB_USER} WITH PASSWORD '${N8N_DB_PASSWORD}';
    CREATE DATABASE ${N8N_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${N8N_DB_NAME} TO ${N8N_DB_USER};
    ALTER DATABASE ${N8N_DB_NAME} OWNER TO ${N8N_DB_USER};
    -- === Gebruiker & Database voor Nextcloud ===
    CREATE USER ${NEXTCLOUD_DB_USER} WITH PASSWORD '${NEXTCLOUD_DB_PASSWORD}';
    CREATE DATABASE ${NEXTCLOUD_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${NEXTCLOUD_DB_NAME} TO ${NEXTCLOUD_DB_USER};
    ALTER DATABASE ${NEXTCLOUD_DB_NAME} OWNER TO ${NEXTCLOUD_DB_USER};
    -- === Gebruiker & Database voor AI Agents ===
    CREATE USER ${AI_AGENTS_DB_USER} WITH PASSWORD '${AI_AGENTS_DB_PASSWORD}';
    CREATE DATABASE ${AI_AGENTS_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${AI_AGENTS_DB_NAME} TO ${AI_AGENTS_DB_USER};
    ALTER DATABASE ${AI_AGENTS_DB_NAME} OWNER TO ${AI_AGENTS_DB_USER};
EOSQL
